name: pulumi
description: pulumi

inputs:
  github-token:
    description: github token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: jdx/mise-action@v2
      with:
        experimental: true
        version: 2025.7.3 # https://github.com/jdx/mise/discussions/5582

    - run: go mod download
      shell: bash
      working-directory: .pulumi

    - name: Preview
      uses: pulumi/actions@v6
      with:
        work-dir: .pulumi
        command: preview
        refresh: true
        stack-name: dev
        color: always

    - name: Up
      if: github.ref_name == github.event.repository.default_branch
      uses: pulumi/actions@v6
      with:
        work-dir: .pulumi
        command: up
        refresh: true
        stack-name: dev
        comment-on-pr: false
        github-token: ${{ inputs.github-token }}
