version: "2"
linters:
  default: all
  disable:
    - wsl
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/anoriqq/pj-tmpl-go/*
formatters:
  enable:
    - gci
    - swaggo
    - golines
    - gofumpt
    - goimports
    - gofmt
output:
  show-stats: false
