version: "2"
linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - varnamelen
    - revive
    - noinlineerr
    - nlreturn
    - perfsprint
    - ireturn
    - gosec
    - godot
    - gochecknoinits
    - mnd
    - gochecknoglobals
    - funcorder
    - exhaustruct
    - errcheck
    - depguard
    - exhaustive
    - contextcheck
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/anoriqq/pj-tmpl-go/*
    varnamelen:
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - c *cli.CLI # 名前衝突を避けるとこれ以上長くも短くもできない
formatters:
  enable:
    - gci
    - swaggo
    - golines
    - gofumpt
    - goimports
    - gofmt
output:
  show-stats: false
