name: 'Go Build and Test'
description: 'Composite action for Go project build and test execution'

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - uses: jdx/mise-action@bfb9fa0b029db830a8c570757cee683df207a6c5 # v2.4.0
      with:
        experimental: true

    - name: Build
      shell: bash
      env:
        RELEASE: 1
      run: make build

    - name: Test
      shell: bash
      run: make test
