name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: jdx/mise-action@v2
      with:
        experimental: true

    - name: Build
      env:
        RELEASE: 1
      run: make build

    - name: Test
      run: make test
