name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'Makefile'                    # CI uses make commands
      - '.github/workflows/**'        # CI config changes
      - 'mise.toml'                   # Tool version changes
      - '**/testdata/**'              # Test data changes

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: jdx/mise-action@v2
      with:
        experimental: true

    - name: Build
      env:
        RELEASE: 1
      run: make build

    - name: Test
      run: make test
